#!/bin/sh

echo "SLPFindSrvs"
rm -f SLPFindSrvs.actual.output
scriptdir=${srcdir}/SLPFindSrvs

test -f ${srcdir}/slpd.pid && kill `cat ${srcdir}/slpd.pid` && rm ${srcdir}/slpd.pid
../slpd/slpd -r ${scriptdir}/slp.test.reg -p ${srcdir}/slpd.pid
RESULT=$?
if test $RESULT != 0; then
    echo "Unable to start slpd (error = $RESULT), test failed."
    exit $RESULT
fi

./testslpfindsrvs service:test >> SLPFindSrvs.actual.output
test -f ${srcdir}/slpd.pid && kill `cat ${srcdir}/slpd.pid` && rm ${srcdir}/slpd.pid
diff -c ${scriptdir}/SLPFindSrvs.expected.output SLPFindSrvs.actual.output
