DEPTH= ..
include $(DEPTH)/defs.mk

PROGRAM= slpd

CSRCS= slpd_cmdline.c \
       slpd_database.c \
	slpd_incoming.c \
	slpd_knownda.c \
       slpd_log.c \
	slpd_outgoing.c \
       slpd_process.c \
       slpd_property.c \
       slpd_regfile.c \
       slpd_socket.c \
	slpd_service.c \
       slpd_main.c

APPLIBS = slp_common libslp

include $(DEPTH)/rules.mk


#all:: $(TARGETS)