#!/bin/bash
rm -f SLPDereg.actual.output
echo SLPDereg
../../slpd/slpd -r slp.test.reg 
./SLPDereg service:registered 10.0.0.1 service:registered 10.0.0.1 >>  SLPDereg.actual.output
echo >> SLPDereg.actual.output
./SLPDereg service:registered 10.0.0.1 service:unregistered 10.0.0.1 >> SLPDereg.actual.output
echo >> SLPDereg.actual.output
./SLPDereg service:test 10.0.0.1 >> SLPDereg.actual.output
killall slpd
diff --brief SLPDereg.expected.output SLPDereg.actual.output
