#!/bin/sh

echo "SLPDereg"
rm -f SLPDereg.actual.output
scriptdir=${srcdir}/SLPDereg

../slpd/slpd -r ${scriptdir}/slp.test.reg 
./slpdereg service:registered 10.0.0.1 service:registered 10.0.0.1 >>  SLPDereg.actual.output
echo >> SLPDereg.actual.output
./slpdereg service:registered 10.0.0.1 service:unregistered 10.0.0.1 >> SLPDereg.actual.output
echo >> SLPDereg.actual.output
./slpdereg service:test 10.0.0.1 >> SLPDereg.actual.output
if test -f /var/run/slpd.pid; then kill `cat /var/run/slpd.pid`; fi
diff -c ${scriptdir}/SLPDereg.expected.output SLPDereg.actual.output
