#!/bin/bash
echo "SLPEscape"
./SLPEscape asdf\(asdf > SLPEscape.actual.output
echo >> SLPEscape.actual.output
./SLPEscape \(asdf >> SLPEscape.actual.output
echo >> SLPEscape.actual.output
./SLPEscape asdf\\ >> SLPEscape.actual.output
echo >> SLPEscape.actual.output
./SLPEscape \(\),\\!\<=\>\~ >> SLPEscape.actual.output
echo >> SLPEscape.actual.output
diff --brief SLPEscape.expected.output SLPEscape.actual.output
