#!/bin/sh

echo "SLPEscape"
rm -f SLPEscape.actual.output
scriptdir=${srcdir}/SLPEscape

./testslpescape asdf\(asdf > SLPEscape.actual.output
echo >> SLPEscape.actual.output
./testslpescape \(asdf >> SLPEscape.actual.output
echo >> SLPEscape.actual.output
./testslpescape asdf\\ >> SLPEscape.actual.output
echo >> SLPEscape.actual.output
./testslpescape \(\),\\!\<=\>\~ >> SLPEscape.actual.output
echo >> SLPEscape.actual.output
diff -c ${scriptdir}/SLPEscape.expected.output SLPEscape.actual.output
