#!/bin/sh

echo "SLPEscape"
rm -f SLPEscape.actual.output
scriptdir=${srcdir}/SLPEscape

./slpescape asdf\(asdf > SLPEscape.actual.output
echo >> SLPEscape.actual.output
./slpescape \(asdf >> SLPEscape.actual.output
echo >> SLPEscape.actual.output
./slpescape asdf\\ >> SLPEscape.actual.output
echo >> SLPEscape.actual.output
./slpescape \(\),\\!\<=\>\~ >> SLPEscape.actual.output
echo >> SLPEscape.actual.output
diff -c ${scriptdir}/SLPEscape.expected.output SLPEscape.actual.output
