#!/bin/sh

echo "SLPFindAttrs"
rm -f SLPFindAttrs.actual.output 
scriptdir=${srcdir}/SLPFindAttrs

../slpd/slpd -r ${scriptdir}/slp.test.reg &
./slpfindattrs service:test 10.0.0.1 foo >> SLPFindAttrs.actual.output
echo >> SLPFindAttrs.actual.output
./slpfindattrs service:test 10.0.0.1 goo >> SLPFindAttrs.actual.output
echo >> SLPFindAttrs.actual.output
./slpfindattrs service:test 10.0.0.1 description >> SLPFindAttrs.actual.output
echo >> SLPFindAttrs.actual.output
./slpfindattrs service:test 10.0.0.1 foo=value1,value2 foo >> SLPFindAttrs.actual.output
echo >> SLPFindAttrs.actual.output
./slpfindattrs service:test 10.0.0.1 foo=value1,value2 goo >> SLPFindAttrs.actual.output
echo >> SLPFindAttrs.actual.output
killall slpd
diff --brief ${scriptdir}/SLPFindAttrs.expected.output SLPFindAttrs.actual.output
