.TH slpd 8 "Sep 08 2001" "OpenSLP 1.0.1"

.SH NAME
slpd \- SLPv2 Service Agent (SA)/Directory Agent (DA)

.SH SYNOPSIS
.B /usr/sbin/slpd 
.B [\-d]
.B [\-c configfile]
.B [\-r registrationfile]
.B [\-l logfile] 
.B [\-p pidfile] 
.B 

.SH DESCRIPTION
.LP
.B slpd
is an SLPv2 compliant Service Agent and (optionally) Directory Agent.  It
listens for SLP requests on port 427, responding to the SLP User Agents and
(when running as a DA) Service Agents.
.B slpd
is typically invoked at boot time, usually out of
.B  /etc/init.d/slpd .
.SH OPTIONS
.TP
.BI \-d 
Don't detach from the controlling tty
.TP
.BI \-f " configfile"
Use configfile as the file slpd reads to obtain configuration information,
rather than the default, 
.B /etc/slpd.conf .
.TP
.BI \-r " registrationfile"
Use registrationfile as the file that slpd reads to obtain static
registrations, rather than the default,  
.BR /etc/slpd.rej .
.TP
.BI \-l " logfile"
Use logfile as the file that slpd reads to write log messages, rather than
the default,  
.B /var/log/slpd.log.
.TP
.BI \-p " pidfile"
Use pidfile as the file that holds the slpd process id, rather than the
default,  
.B /var/run/slpd.pid.

.SH SEE ALSO
"OpenSLP User's Guide"

.SH NOTES
This man page was written for the Debian project by Debian Developer Ganesan
Rajagopal (rganesan@debian.org). You should refer to the online html
documentation in the 
.BR openslp-doc 
package for more complete and up-to-date information.

.SH BUGS
http://sourceforge.net/tracker/?group_id=1730&atid=101730

.SH ACKNOWLEDGEMENTS
.B OpenSLP
is developed and maintained by The OpenSLP Project (http://www.openslp.org/).
