#!/bin/sh

echo "SLPParseSrvURL"
rm -f SLPParseSrvURL.actual.output
scriptdir=${srcdir}/SLPParseSrvURL

(
  ./testslpparsesrvurl service:test://10.0.0.1
  echo
  ./testslpparsesrvurl service:test1:test2://10.0.0.1:80
  echo
  ./testslpparsesrvurl service:test://10.0.0.1:80/foo/goo
  echo
  ./testslpparsesrvurl service:test://10.0.0.1/foo/goo
) > SLPParseSrvURL.actual.output

diff -c ${scriptdir}/SLPParseSrvURL.expected.output SLPParseSrvURL.actual.output
