/*-------------------------------------------------------------------------
 * Copyright (C) 2000 Caldera Systems, Inc
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 *    Neither the name of Caldera Systems nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * `AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE CALDERA
 * SYSTEMS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;  LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *-------------------------------------------------------------------------*/

/** Internal implementation for generating unique XIDs.
 *
 * Provides functions that are supposed to generate 16-bit values that 
 * won't be generated for a long time in this process and hopefully won't 
 * be generated by other process for a long time.
 *
 * @file       slp_xid.c
 * @author     John Calcote (jcalcote@novell.com)
 * @attention  Please submit patches to http://www.openslp.org
 * @ingroup    CommonCodeXID
 */

#include "slp_types.h"
#include "slp_xid.h"
#include "slp_pid.h"

/** The last returned transaction id (XID) value. 
 */
static uint16_t G_Xid = 0;

/** Seeds the transaction id (XID) generator.
 *
 * Should only be called once per process, at startup.
 */
void SLPXidSeed(void)
{
   /* Psuedo random number generation without side-effects */
   const uint32_t PRIME = 17977;
   G_Xid = (uint16_t)(SLPPidGet() * clock() * PRIME);
}

/** Returns the next serial transaction id (XID).
 *
 * @return A serialized 16-bit value. 
 *
 * @todo Needs an atomic to be thread-safe.
 */
uint16_t SLPXidGenerate(void) { return ++G_Xid; }

/*=========================================================================*/
