/***************************************************************************/
/*                                                                         */
/* Project:     OpenSLP - OpenSource implementation of Service Location    */
/*              Protocol                                                   */
/*                                                                         */
/* File:        slplib_xid.c                                               */
/*                                                                         */
/* Abstract:    Internal implementation for generating unique XIDs.        */
/*              Provides functions that are supposed to generate 16-bit    */
/*              values that won't be generated for a long time in this     */
/*              process and hopefully won't be generated by other process  */ 
/*              for a long time.                                           */
/*                                                                         */
/*-------------------------------------------------------------------------*/
/*                                                                         */
/* Copyright (c) 1995, 1999  Caldera Systems, Inc.                         */
/*                                                                         */
/* This program is free software; you can redistribute it and/or modify it */
/* under the terms of the GNU Lesser General Public License as published   */
/* by the Free Software Foundation; either version 2.1 of the License, or  */
/* (at your option) any later version.                                     */
/*                                                                         */
/*     This program is distributed in the hope that it will be useful,     */
/*     but WITHOUT ANY WARRANTY; without even the implied warranty of      */
/*     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       */
/*     GNU Lesser General Public License for more details.                 */
/*                                                                         */
/*     You should have received a copy of the GNU Lesser General Public    */
/*     License along with this program; see the file COPYING.  If not,     */
/*     please obtain a copy from http://www.gnu.org/copyleft/lesser.html   */
/*                                                                         */
/*-------------------------------------------------------------------------*/
/*                                                                         */
/*     Please submit patches to http://www.openslp.org                     */
/*                                                                         */
/***************************************************************************/

#ifdef WIN32
#include <windows.h>
#include <stdlib.h>
#else
#include <stdlib.h>
#include <unistd.h>
#endif

#include <slp_xid.h>

/*=========================================================================*/
int G_Xid = 0;
/* Global variable that is incremented before SLPGenerateXid() returns     */
/*=========================================================================*/


/*=========================================================================*/
void SLPXidSeed()
/* Seeds the XID generator.  Should only be called 1 time per process!     */
/* currently called when the first handle is opened.                       */
/*=========================================================================*/
{
    /* Generate a random start*/
#ifdef WIN32
   srand(GetCurrentProcessId() | G_Xid);   
   G_Xid = (unsigned short)rand();
#else
    srandom(getpid() | G_Xid);   
    G_Xid = (unsigned short)random();
#endif
}


/*=========================================================================*/
unsigned short SLPXidGenerate()
/*                                                                         */
/* Returns: A 16-bit value                                                 */
/*=========================================================================*/
{
    G_Xid++;
    return G_Xid;
}



