#############################################################################
#
# Top level make file for the openslp project
#
# Currently, this make file will build a OpenSLP for Linux.  We hope to 
# use automake and autoconf in the future.
#############################################################################

release :            

debug: 

install: release
	chmod a+x install.sh
	./install.sh 
	
clean: 


