#!/bin/sh

echo "SLPFindSrvTypes"
rm -f SLPFindSrvTypes.actual.output
scriptdir=${srcdir}/SLPFindSrvTypes

../slpd/slpd -r ${scriptdir}/slp.test.reg &
./slpfindsrvtypes "*" >> SLPFindSrvTypes.actual.output
echo >> SLPFindSrvTypes.actual.output
./slpfindsrvtypes "" >> SLPFindSrvTypes.actual.output
echo >> SLPFindSrvTypes.actual.output
./slpfindsrvtypes "JUNK" >> SLPFindSrvTypes.actual.output
echo >> SLPFindSrvTypes.actual.output
./slpfindsrvtypes "OPENSLP" >> SLPFindSrvTypes.actual.output

if test -f /var/run/slpd.pid; then kill `cat /var/run/slpd.pid`; fi
diff -c ${scriptdir}/SLPFindSrvTypes.expected.output SLPFindSrvTypes.actual.output
