#!/bin/sh

echo "SLPReg"
rm -f SLPReg.actual.output
scriptdir=${srcdir}/SLPReg

../slpd/slpd &
./slpreg service:valid 10.0.0.1 service:valid >>  SLPReg.actual.output
echo >> SLPReg.actual.output
./slpreg service:valid 10.0.0.1 service:invalid >> SLPReg.actual.output
if test -f /var/run/slpd.pid; then kill `cat /var/run/slpd.pid`; fi
diff -c ${scriptdir}/SLPReg.expected.output SLPReg.actual.output
