#!/bin/sh

echo "SLPUnescape"
rm -f SLPUnescape.actual.output
scriptdir=${srcdir}/SLPUnescape

./testslpunescape asdfasdf > SLPUnescape.actual.output
echo >> SLPUnescape.actual.output
./testslpunescape \\28abc >> SLPUnescape.actual.output
echo >> SLPUnescape.actual.output
./testslpunescape abc\\7E >> SLPUnescape.actual.output
echo >> SLPUnescape.actual.output
./testslpunescape \\28\\29\\2C\\5C\\21\\3C\\3D\\3E\\7E >> SLPUnescape.actual.output
echo >> SLPUnescape.actual.output
diff -c ${scriptdir}/SLPUnescape.expected.output SLPUnescape.actual.output
