#!/bin/sh

echo "SLPUnescape"
rm -f SLPUnescape.actual.output
scriptdir=${srcdir}/SLPUnescape

./slpunescape asdfasdf > SLPUnescape.actual.output
echo >> SLPUnescape.actual.output
./slpunescape \\28abc >> SLPUnescape.actual.output
echo >> SLPUnescape.actual.output
./slpunescape abc\\7E >> SLPUnescape.actual.output
echo >> SLPUnescape.actual.output
./slpunescape \\28\\29\\2C\\5C\\21\\3C\\3D\\3E\\7E >> SLPUnescape.actual.output
echo >> SLPUnescape.actual.output
diff --brief ${scriptdir}/SLPUnescape.expected.output SLPUnescape.actual.output
